#!/usr/bin/env python3
"""
Canonical MBBS / NEET PG subject + topic taxonomy.

Subjects match the user's taught list (19 subjects). Topics are high-yield
internal divisions drawn from common NEET PG coaching syllabi
(PrepLadder / CollegeDekho / Careers360 style).
"""

from __future__ import annotations

# Exact taught subjects (canonical display names)
MBBS_SUBJECTS = [
    "Anatomy",
    "Biochemistry",
    "Physiology",
    "Pharmacology",
    "Microbiology",
    "Pathology",
    "Community Medicine",
    "Forensic Medicine",
    "Ophthalmology",
    "ENT",
    "Medicine",
    "Surgery",
    "OBG",
    "Pediatrics",
    "Anaesthesia",
    "Orthopedics",
    "Radiology",
    "Psychiatry",
    "Dermatology",
]

# Map every historical / OCR / LLM spelling → canonical MBBS subject
SUBJECT_ALIASES: dict[str, str] = {
    # identity
    **{s: s for s in MBBS_SUBJECTS},
    **{s.lower(): s for s in MBBS_SUBJECTS},
    # Medicine
    "general medicine": "Medicine",
    "medicine": "Medicine",
    "internal medicine": "Medicine",
    "mredicine": "Medicine",
    "mediciene": "Medicine",
    "emergency medicine": "Medicine",
    "chest medicine": "Medicine",
    "tb & chest": "Medicine",
    "endocrinology": "Medicine",
    "neurology": "Medicine",
    "cardiology": "Medicine",
    "nephrology": "Medicine",
    "pulmonology": "Medicine",
    "gastroenterology": "Medicine",
    "hematology": "Medicine",
    "rheumatology": "Medicine",
    "infectious": "Medicine",
    "infectious diseases": "Medicine",
    # Surgery
    "general surgery": "Surgery",
    "surgery": "Surgery",
    "surgery d": "Surgery",
    "surgery p": "Surgery",
    # OBG
    "obg": "OBG",
    "obstetrics": "OBG",
    "gynaecology": "OBG",
    "gynecology": "OBG",
    "obstetrics & gynaecology": "OBG",
    "obstetrics and gynaecology": "OBG",
    "obstetrics & gynecology": "OBG",
    "gynaecology & obstetrics": "OBG",
    "obgyn": "OBG",
    # Pediatrics / Orthopedics / ENT / Anaesthesia
    "paediatrics": "Pediatrics",
    "pediatrics": "Pediatrics",
    "orthopaedics": "Orthopedics",
    "orthopedic": "Orthopedics",
    "orthopedics": "Orthopedics",
    "ent": "ENT",
    "anesthesia": "Anaesthesia",
    "anaesthesia": "Anaesthesia",
    "anaesthesiology": "Anaesthesia",
    "anesthesiology": "Anaesthesia",
    # Community / Forensic
    "community medicine": "Community Medicine",
    "psm": "Community Medicine",
    "spm": "Community Medicine",
    "forensic medicine": "Forensic Medicine",
    "forensic": "Forensic Medicine",
    "fmt": "Forensic Medicine",
    # Radiology
    "radio-diagnosis": "Radiology",
    "radiodiagnosis": "Radiology",
    # Dermatology
    "venereology": "Dermatology",
    "skin": "Dermatology",
    # noise
    "mixed": "Unknown",
    "unknown": "Unknown",
    "general": "Unknown",
}

# High-yield topics within each subject (syllabus-style)
SUBJECT_TOPICS: dict[str, list[str]] = {
    "Anatomy": [
        "Upper Limb",
        "Lower Limb",
        "Thorax",
        "Abdomen",
        "Head & Neck",
        "Neuroanatomy",
        "Embryology",
        "Histology",
        "Pelvis & Perineum",
        "Osteology",
    ],
    "Biochemistry": [
        "Carbohydrate Metabolism",
        "Lipid Metabolism",
        "Protein Metabolism",
        "Enzymology",
        "Genetics & Molecular Biology",
        "Vitamins & Nutrition",
        "Heme Metabolism",
        "Acid-Base & Buffer",
    ],
    "Physiology": [
        "Cardiovascular",
        "Respiratory",
        "Renal",
        "Gastrointestinal",
        "Nerve Muscle",
        "Endocrine",
        "Reproductive",
        "CNS Physiology",
        "Blood & Immunity",
        "Special Senses",
    ],
    "Pharmacology": [
        "General Pharmacology",
        "Autonomic",
        "Cardiovascular Drugs",
        "CNS Drugs",
        "Antimicrobials",
        "Chemotherapy & Anticancer",
        "Endocrine Pharmacology",
        "Autacoids",
        "Toxicology",
    ],
    "Microbiology": [
        "Bacteriology",
        "Virology",
        "Parasitology",
        "Mycology",
        "Immunology",
        "Sterilization & Hospital Infection",
        "Vaccines",
    ],
    "Pathology": [
        "Cell Injury & Death",
        "Inflammation & Healing",
        "Neoplasia",
        "Hematopathology",
        "Immunopathology",
        "Systemic Pathology",
        "Genetics Pathology",
    ],
    "Community Medicine": [
        "Epidemiology",
        "Biostatistics",
        "National Health Programs",
        "Nutrition & Health",
        "Environment & Occupational Health",
        "Demography & Family Planning",
        "Health Care Delivery",
    ],
    "Forensic Medicine": [
        "Thanatology",
        "Injuries & Trauma",
        "Toxicology",
        "Sexual Offences",
        "Legal Procedures",
        "Identification",
    ],
    "Ophthalmology": [
        "Cornea & Refractive",
        "Lens & Cataract",
        "Glaucoma",
        "Retina",
        "Uvea",
        "Neuro-ophthalmology",
        "Squint & Pediatric Ophthalmology",
    ],
    "ENT": [
        "Ear",
        "Nose & PNS",
        "Throat & Larynx",
        "Head & Neck",
        "Audiology",
    ],
    "Medicine": [
        "Cardiology",
        "Neurology",
        "Pulmonology",
        "Gastroenterology",
        "Nephrology",
        "Endocrinology",
        "Hematology",
        "Infectious Diseases",
        "Rheumatology",
        "Critical Care",
    ],
    "Surgery": [
        "Gastrointestinal Surgery",
        "Urology",
        "Hernia & Abdominal Wall",
        "Breast & Endocrine Surgery",
        "Trauma Surgery",
        "Vascular",
        "Oncology Surgery",
        "Burns & Plastic",
    ],
    "OBG": [
        "Antenatal Care",
        "Labor & Delivery",
        "Obstetric Complications",
        "Menstrual Disorders",
        "Infertility",
        "Contraception",
        "Gynecologic Oncology",
        "Urogynecology",
    ],
    "Pediatrics": [
        "Neonatology",
        "Growth & Development",
        "Pediatric Infectious",
        "Pediatric Respiratory",
        "Pediatric Nutrition",
        "Pediatric Cardiology",
        "Immunization",
    ],
    "Anaesthesia": [
        "General Anaesthesia",
        "Regional Anaesthesia",
        "Airway Management",
        "Critical Care",
        "Pain Management",
        "Local Anaesthetics",
    ],
    "Orthopedics": [
        "Fractures",
        "Joints & Arthritis",
        "Spine",
        "Pediatric Orthopedics",
        "Trauma",
        "Infections of Bone & Joint",
    ],
    "Radiology": [
        "X-ray",
        "CT",
        "MRI",
        "Ultrasound",
        "Nuclear Medicine",
        "Interventional Radiology",
    ],
    "Psychiatry": [
        "Mood Disorders",
        "Schizophrenia & Psychosis",
        "Anxiety & OCD",
        "Substance Use",
        "Child Psychiatry",
        "Personality Disorders",
        "Psychopharmacology",
    ],
    "Dermatology": [
        "Infections of Skin",
        "Papulosquamous",
        "Bullous Disorders",
        "Pigmentary Disorders",
        "STDs",
        "Leprosy",
        "Appendageal Disorders",
    ],
}


def normalize_subject(raw: str | None) -> str:
    if not raw:
        return "Unknown"
    s = str(raw).strip()
    if not s:
        return "Unknown"
    hit = SUBJECT_ALIASES.get(s) or SUBJECT_ALIASES.get(s.lower())
    if hit:
        return hit
    return "Unknown"


def topic_to_subject_map() -> dict[str, str]:
    """Primary subject for each curated topic name."""
    out: dict[str, str] = {}
    for subj, topics in SUBJECT_TOPICS.items():
        for t in topics:
            out[t] = subj
    # common aliases seen in data
    extras = {
        "Genetics": "Biochemistry",
        "Trauma": "Orthopedics",
        "Toxicology": "Pharmacology",
        "Infectious Disease": "Medicine",
        "Pregnancy": "OBG",
        "Labor & Delivery": "OBG",
        "Menstrual": "OBG",
        "Infertility": "OBG",
        "Contraception": "OBG",
        "Tumor": "OBG",
        "Growth & Nutrition": "Pediatrics",
        "Pediatric Infectious": "Pediatrics",
        "Pediatric Respiratory": "Pediatrics",
        "Development": "Pediatrics",
        "Gastrointestinal Surgery": "Surgery",
        "Urology": "Surgery",
        "Cardiothoracic": "Surgery",
        "Endocrine Surgery": "Surgery",
        "Oncology Surgery": "Surgery",
        "Trauma Surgery": "Surgery",
        "Joints": "Orthopedics",
        "Pediatric Ortho": "Orthopedics",
        "Fractures": "Orthopedics",
        "Spine": "Orthopedics",
        "Cornea & Refractive": "Ophthalmology",
        "Retina": "Ophthalmology",
        "Lens": "Ophthalmology",
        "Glaucoma": "Ophthalmology",
        "Ear": "ENT",
        "Nose": "ENT",
        "Throat ENT": "ENT",
        "Head & Neck ENT": "ENT",
        "X-ray": "Radiology",
        "CT & MRI": "Radiology",
        "Ultrasound": "Radiology",
        "Intervention": "Radiology",
        "General": "Anaesthesia",
        "Regional": "Anaesthesia",
        "Local": "Anaesthesia",
        "Critical Care": "Anaesthesia",
        "Thanatology": "Forensic Medicine",
        "Legal": "Forensic Medicine",
        "Toxicology Forensic": "Forensic Medicine",
        "Epidemiology": "Community Medicine",
        "Biostatistics": "Community Medicine",
        "Health Programs": "Community Medicine",
        "Nutrition & Health": "Community Medicine",
        "Environment": "Community Medicine",
        "Dermatology": "Dermatology",
        "Psychiatry": "Psychiatry",
        "Cardiovascular": "Physiology",
        "Obstetrics": "OBG",
        "Gynaecology": "OBG",
        "Neonatology": "Pediatrics",
        "Immunology": "Microbiology",
        "Bacteriology": "Microbiology",
        "Virology": "Microbiology",
        "Parasitology": "Microbiology",
        "Mycology": "Microbiology",
        "Neoplasia": "Pathology",
        "Inflammation & Healing": "Pathology",
        "Hematopathology": "Pathology",
        "Cell Injury & Death": "Pathology",
        "Autonomic": "Pharmacology",
        "Antimicrobials": "Pharmacology",
        "CNS": "Pharmacology",
        "Chemotherapy": "Pharmacology",
        "Neuroanatomy": "Anatomy",
        "Embryology": "Anatomy",
        "Histology": "Anatomy",
        "Upper Limb": "Anatomy",
        "Lower Limb": "Anatomy",
        "Thorax": "Anatomy",
        "Abdomen": "Anatomy",
        "Head & Neck": "Anatomy",
        "Cardiology": "Medicine",
        "Neurology": "Medicine",
        "Nephrology": "Medicine",
        "Pulmonology": "Medicine",
        "Gastroenterology": "Medicine",
        "Endocrinology": "Medicine",
        "Hematology": "Medicine",
        "Infectious Diseases": "Medicine",
        "Carbohydrate Metabolism": "Biochemistry",
        "Lipid Metabolism": "Biochemistry",
        "Protein Metabolism": "Biochemistry",
        "Enzymology": "Biochemistry",
        "Nutrition": "Biochemistry",
        "Respiratory": "Physiology",
        "Renal": "Physiology",
        "Gastrointestinal": "Physiology",
        "Nerve Muscle": "Physiology",
        "Endocrine": "Physiology",
        "Reproductive": "Physiology",
        "Blood": "Physiology",
    }
    out.update(extras)
    return out
