TOPIC_RULES = {
    "Anatomy": {
        "Upper Limb": [
            "brachial plexus",
            "median nerve",
            "ulnar nerve",
            "radial nerve",
            "axillary nerve",
            "musculocutaneous",
            "hand anatomy",
            "arm anatomy",
            "forearm",
            "wrist",
            "elbow joint",
            "carpal tunnel",
            "thenar",
            "hypothenar",
        ],
        "Lower Limb": [
            "femoral nerve",
            "sciatic nerve",
            "tibial nerve",
            "peroneal",
            "sciatic notch",
            "gluteal",
            "thigh",
            "leg",
            "foot anatomy",
            "ankle",
            "knee joint",
            "hip joint",
            "popliteal",
        ],
        "Thorax": [
            "heart",
            "lung",
            "mediastinum",
            "diaphragm",
            "pleura",
            "bronchi",
            "trachea",
            "cardiac",
            "thoracic duct",
        ],
        "Abdomen": [
            "stomach",
            "liver",
            "gallbladder",
            "pancreas",
            "spleen",
            "intestine",
            "colon",
            "appendix",
            "peritoneum",
            "mesentery",
            "kidney",
            "hepatic",
            "biliary",
        ],
        "Head & Neck": [
            "skull",
            "scalp",
            "face",
            "neck",
            "thyroid",
            "parathyroid",
            "cervical",
            "mandible",
            "maxilla",
            "temporomandibular",
            "pharyngeal",
            "laryngeal",
        ],
        "Neuroanatomy": [
            "brain",
            "spinal cord",
            "cerebrum",
            "cerebellum",
            "ventricle",
            "meninges",
            "cns",
            "cerebral",
            "brainstem",
            "thalamus",
            "hypothalamus",
        ],
        "Histology": [
            "microscopy",
            "histology",
            "tissue",
            "microscopic",
            "cell structure",
            "epithelium",
            "stroma",
        ],
        "Embryology": [
            "embryo",
            "embryology",
            "fetal development",
            "gastrulation",
            "organogenesis",
        ],
    },
    "Physiology": {
        "Cardiovascular": [
            "cardiac",
            "heart rate",
            "blood pressure",
            "cardiac output",
            "ecg",
            "ejection fraction",
            "stroke volume",
            " preload",
            "afterload",
            "heart sound",
            "systole",
            "diastole",
            "cardiac cycle",
            "coronary",
        ],
        "Respiratory": [
            "respiration",
            "ventilation",
            "lung volume",
            "vital capacity",
            "tidal volume",
            "peep",
            "oxygen",
            "co2",
            "gas exchange",
            "alveoli",
            "bronchiole",
            "pulmonary",
            "respiratory rate",
            "pef",
            "fv",
        ],
        "Gastrointestinal": [
            "gi motility",
            "peristalsis",
            "gastric",
            "intestinal",
            "digestion",
            "absorption",
            "gi secretion",
            "gastro",
            "intestinal motility",
            "bowel",
        ],
        "Renal": [
            "kidney",
            "glomerular",
            "gfr",
            "renin",
            "angiotensin",
            "urine",
            "tubular",
            "nephron",
            "osmolality",
            "diuretic",
            "clearance",
            "creatinine",
        ],
        "Nerve Muscle": [
            "neuromuscular",
            "motor end plate",
            "nerve conduction",
            "synapse",
            "neurotransmitter",
            "acetylcholine",
            "muscle contraction",
            "action potential",
            "depolarization",
            "repolarization",
            "refractory",
            "electrolyte imbalance",
        ],
        "Endocrine": [
            "hormone",
            "thyroid",
            "adrenal",
            "pituitary",
            "parathyroid",
            "cortisol",
            "insulin",
            "glucagon",
            "testosterone",
            "estrogen",
            "progesterone",
            "gnrh",
            "lh",
            "fsh",
            "acth",
            "tsh",
            "gh",
            "hormonal",
        ],
        "Reproductive": [
            "spermatogenesis",
            "oogenesis",
            "menstrual",
            "ovulation",
            "semen",
            "sperm",
            "fertile",
            "contraception physiology",
            "reproductive hormone",
        ],
        "Blood": [
            "hemoglobin",
            "blood group",
            "coagulation",
            "bleeding time",
            "clotting",
            "platelet",
            "anemia",
            "polycythemia",
            "erythrocyte",
            "leukocyte",
        ],
    },
    "Biochemistry": {
        "Carbohydrate Metabolism": [
            "glycolysis",
            "gluconeogenesis",
            "glycogen",
            "tca cycle",
            "krebs",
            "electron transport",
            "atp synthesis",
            "glucose",
            "insulin biochemistry",
            "glucokinase",
            "hexokinase",
            "pyruvate",
        ],
        "Lipid Metabolism": [
            "cholesterol",
            "triglyceride",
            "fatty acid",
            "beta oxidation",
            "ketone",
            "lipoprotein",
            "hdl",
            "ldl",
            "vldl",
            "bile acid",
            "steroid",
        ],
        "Protein Metabolism": [
            "amino acid",
            "protein synthesis",
            "transamination",
            "urea cycle",
            "ammonia",
            "creatinine biochemistry",
            "gel electrophoresis",
            "chromatography",
        ],
        "Enzymology": [
            "enzyme",
            "kinetics",
            "michaelis",
            "km value",
            "vmax",
            "coenzyme",
            "cofactor",
            "vitamin coenzyme",
        ],
        "Genetics": [
            "dna",
            "rna",
            "gene",
            "chromosome",
            "genetic code",
            "mutation",
            "replication",
            "transcription",
            "translation",
            "pcr",
            "recombinant dna",
            "gene therapy",
            "genetic disorder",
            "pedigree",
        ],
        "Nutrition": [
            "vitamins",
            "mineral",
            "nutritional",
            "calorie",
            "malnutrition",
            "bmr",
            "basal metabolic",
        ],
    },
    "Pathology": {
        "Cell Injury & Death": [
            "cell injury",
            "necrosis",
            "apoptosis",
            "gangrene",
            "atrophy",
            "hypertrophy",
            "hyperplasia",
            "metaplasia",
            "dysplasia",
            "reversible",
            "irreversible",
            "free radical",
        ],
        "Inflammation & Healing": [
            "inflammation",
            "acute",
            "chronic",
            "granuloma",
            "wound healing",
            " руб",
            "exudate",
            "transudate",
            "edema",
            "swelling",
            "abscess",
            "cellulitis",
            "healing",
        ],
        "Neoplasia": [
            "tumor",
            "cancer",
            "carcinoma",
            "sarcoma",
            "benign",
            "malignant",
            "metastasis",
            "neoplastic",
            "oncology",
            "polyp",
            "dysplasia",
            "tumor marker",
            "grade",
            "stage",
        ],
        "Hematopathology": [
            "leukemia",
            "lymphoma",
            "myeloma",
            "anemia",
            "hemoglobinopathy",
            "coagulation disorder",
            "bleeding disorder",
            "thrombocytopenia",
            "hemophilia",
            "myeloproliferative",
            "aplasia",
        ],
        "Immunopathology": [
            "autoimmune",
            "hypersensitivity",
            "immunodeficiency",
            "hiv",
            "aids",
            "lupus",
            "rheumatoid",
            "sle",
            "graft",
            "transplant rejection",
            "immune deficiency",
        ],
    },
    "Pharmacology": {
        "Autonomic": [
            "adrenergic",
            "cholinergic",
            "sympathomimetic",
            "parasympathomimetic",
            "atropine",
            "adrenaline",
            "noradrenaline",
            "dopamine",
            "dobutamine",
            "muscarinic",
            "nicotinic",
            "phenylephrine",
        ],
        "Cardiovascular": [
            "antihypertensive",
            "diuretic",
            "beta blocker",
            "ace inhibitor",
            "arb",
            "ccb",
            "calcium channel",
            "digoxin",
            "antiarrhythmic",
            "warfarin",
            "heparin",
            "statin",
            "nitrate",
            "isosorbide",
        ],
        "Antimicrobials": [
            "antibiotic",
            "antimicrobial",
            "penicillin",
            "cephalosporin",
            "aminoglycoside",
            "fluoroquinolone",
            "macrolide",
            "tetracycline",
            "sulfonamide",
            "antifungal",
            "antiviral",
            "antimalarial",
            "antitubercular",
            "art",
            "haart",
            "azithromycin",
            "vancomycin",
            "chloroquine",
            "rifampicin",
            "itraconazole",
        ],
        "CNS": [
            "antidepressant",
            "antipsychotic",
            "anxiolytic",
            "sedative",
            "hypnotic",
            "anticonvulsant",
            "antiepileptic",
            "opioid",
            "narcotic",
            "anesthetic",
            "benzodiazepine",
            "ssri",
            "tricyclic",
            "phenytoin",
            "lamotrigine",
            "levetiracetam",
            "diazepam",
            "midazolam",
            "morphine",
            "fentanyl",
            "tramadol",
        ],
        "Chemotherapy": [
            "chemotherapy",
            "anticancer",
            "alkylating",
            "antimetabolite",
            "methotrexate",
            "cyclophosphamide",
            "cisplatin",
            "doxorubicin",
            "imatinib",
            "rituximab",
            "vincristine",
            "alkylating agent",
        ],
        "Toxicology": [
            "poisoning",
            "toxicity",
            "overdose",
            "antidote",
            "heavy metal",
            "organophosphate",
            "cyanide",
            "carbon monoxide",
            "alcohol toxicity",
            "op poisoning",
            "benzodiazepine overdose",
            "organophosphorus",
        ],
    },
    "Microbiology": {
        "Bacteriology": [
            "bacteria",
            "bacterial",
            "gram stain",
            "gram positive",
            "gram negative",
            "staphylococcus",
            "streptococcus",
            "pneumococcus",
            "neisseria",
            "e coli",
            "klebsiella",
            "pseudomonas",
            "clostridium",
            "bacillus",
            "mycobacterium",
            "tuberculosis",
            "diphtheria",
            " Bordetella",
            "vibrio",
            "cholera",
            "shigella",
            "salmonella",
            "helicobacter",
        ],
        "Virology": [
            "virus",
            "viral",
            "hiv",
            "hsv",
            "hbv",
            "hcv",
            "influenza",
            "coronavirus",
            "covid",
            "dengue",
            "chikungunya",
            "measles",
            "mumps",
            "rubella",
            "polio",
            "rabies",
            "hepatitis",
            "herpes",
            "varicella",
            "ebv",
            "cmv",
            "hpv",
            "retrovirus",
            "arbovirus",
        ],
        "Parasitology": [
            "parasite",
            "parasitic",
            "malaria",
            "plasmodium",
            "ameb",
            "giardia",
            "helminth",
            "worm",
            "ascaris",
            "ankylostoma",
            "worm",
            "ectoparasite",
            "lice",
            "scabies",
            "leishmania",
            "trypanosoma",
            "toxoplasma",
            "cryptosporidium",
            "hydatid",
            "taenia",
            "fasciola",
            "schistosomiasis",
        ],
        "Mycology": [
            "fungus",
            "fungal",
            "candida",
            "aspergillus",
            "cryptococcus",
            "histoplasma",
            "blastomyces",
            "dermatophyte",
            "mucormycosis",
            "mycotic",
            "tinea",
            "ringworm",
        ],
        "Immunology": [
            "antibody",
            "antigen",
            "complement",
            "cytokine",
            "igm",
            "igg",
            "iga",
            "ige",
            "vaccine",
            "immunization",
            "immune response",
            "hypersensitivity",
            "cell mediated",
            "humoral",
            "mhc",
            "hla",
            "antigen presenting",
        ],
    },
    "Forensic Medicine": {
        "Thanatology": [
            "death",
            "autopsy",
            "postmortem",
            "rigor mortis",
            "livor mortis",
            "algor mortis",
            "putrefaction",
            "decomposition",
            "mummification",
            "adipocere",
            "time since death",
            "pmi",
        ],
        "Toxicology Forensic": [
            "forensic toxicology",
            "poison",
            "medicolegal",
            "organophosphate poisoning",
            "cyanide poisoning",
            "heavy metal poisoning",
            "corrosive poisoning",
            "alkaloid poisoning",
            "date rape",
        ],
        "Trauma": [
            "injury",
            "wound",
            "laceration",
            "abrasion",
            "contusion",
            "fracture forensic",
            "firearm",
            "bullet",
            "blunt trauma",
            "sharp injury",
            "haematoma",
            "head injury",
            "abdominal injury",
        ],
        "Legal": [
            "legal medicine",
            "IPC",
            "CrPC",
            "Pocso",
            "rape",
            "sexual assault",
            "forensic",
            "medicolegal",
            "negligence",
            "mci",
            "professional misconduct",
            "consumer protection",
        ],
    },
    "Community Medicine": {
        "Epidemiology": [
            "epidemiology",
            "epidemic",
            "pandemic",
            "outbreak",
            "endemic",
            "incidence",
            "prevalence",
            "attack rate",
            "mortality",
            "morbidity",
            "odds ratio",
            "relative risk",
            "attribution",
            "screening",
            "surveillance",
        ],
        "Biostatistics": [
            "statistics",
            "mean",
            "median",
            "mode",
            "standard deviation",
            "p value",
            "confidence interval",
            "hypothesis",
            "t test",
            "chi square",
            "sensitivity",
            "specificity",
            "ppv",
            "npv",
            "likelihood ratio",
            "odds",
            "regression",
        ],
        "Health Programs": [
            "national health",
            "health program",
            "nmhp",
            "nrhp",
            "rch",
            "mch",
            "immunization program",
            "pulse polio",
            "ayushman",
            "jhpiego",
            "nhp",
            "universal health",
        ],
        "Nutrition & Health": [
            "nutrition",
            "protein energy",
            "pem",
            "marasmus",
            "kwashiorkor",
            "vitamins deficiency",
            "iodine deficiency",
            "iron deficiency",
            "anemia prophylaxis",
            "calorie",
            "balanced diet",
            "bmi",
        ],
        "Environment": [
            "environmental health",
            "sanitation",
            "water supply",
            "sewage",
            "waste management",
            "air pollution",
            "radiation",
            "occupational health",
            "lead poisoning",
            "noise pollution",
        ],
    },
    "General Medicine": {
        "Cardiology": [
            "cardiac",
            "heart disease",
            "mi",
            "myocardial infarction",
            "angina",
            "heart failure",
            "chf",
            "arrhythmia",
            "atrial fibrillation",
            "heart block",
            "valvular",
            "aortic",
            "mitral",
            "endocarditis",
            "pericarditis",
            "cardiomyopathy",
            "hypertension",
            "coronary artery",
            "ecg medicine",
            " cardiac catheterization",
            "angiography",
        ],
        "Neurology": [
            "stroke",
            "cva",
            "seizure",
            "epilepsy",
            "meningitis",
            "encephalitis",
            "brain tumor neurology",
            "headache",
            "migraine",
            "tension headache",
            "neuropathy",
            "peripheral neuropathy",
            "gbs",
            "guillain barre",
            "myasthenia",
            "multiple sclerosis",
            "parkinson",
            "dementia",
            "alzheimer",
            "cns infection",
            "neurosyphilis",
            "neurocysticercosis",
        ],
        "Nephrology": [
            "kidney disease",
            "renal failure",
            "aki",
            "ckd",
            "nephritic",
            "nephrotic",
            "nephritis",
            "nephrotic syndrome",
            "glomerulonephritis",
            "pyelonephritis",
            "dialysis",
            "renal transplant",
            "kidney stone",
            "urolithiasis",
        ],
        "Pulmonology": [
            "pneumonia",
            "tb",
            "tuberculosis",
            "lung disease",
            "copd",
            "asthma",
            "bronchitis",
            "pleural effusion",
            "pneumothorax",
            "sarcoidosis",
            "interstitial lung",
            "respiratory failure",
            "ards",
            "lung cancer",
            "sleep apnea",
        ],
        "Gastroenterology": [
            "liver disease",
            "hepatitis",
            "cirrhosis",
            "jaundice",
            "portal hypertension",
            "ascites",
            "esophageal varices",
            "gerd",
            "peptic ulcer",
            "gastritis",
            "ibd",
            "crohn",
            "ulcerative colitis",
            "diarrhea",
            "malabsorption",
            "pancreatitis",
            "gi bleeding",
        ],
        "Endocrinology": [
            "diabetes",
            "thyroid disease",
            "hyperthyroid",
            "hypothyroid",
            "goiter",
            "cushing",
            "addison",
            "adrenal insufficiency",
            "acromegaly",
            "gigantism",
            "pheochromocytoma",
            "hyperparathyroid",
            "hypopituitarism",
            "diabetes mellitus",
            "t1dm",
            "t2dm",
            "diabetic ketoacidosis",
        ],
        "Hematology": [
            "anemia medicine",
            "hemoglobinopathy",
            "thalassemia",
            "sickle cell",
            "hemophilia medicine",
            "coagulation medicine",
            "thrombocytopenia medicine",
            "leukemia medicine",
            "lymphoma medicine",
            "myeloma medicine",
            "bone marrow",
            "aplasia medicine",
            "pancytopenia",
        ],
        "Dermatology": [
            "skin disease",
            "eczema",
            "dermatitis",
            "psoriasis",
            "vitiligo",
            "leprosy",
            " Hans disease",
            "dermatophyte",
            "tinea",
            "scabies",
            "leishmaniasis",
            "skin infection",
            "staph skin",
            "herpes skin",
            "syphilis skin",
            "chancre",
            "condyloma",
            "wart",
            "hpv skin",
            "urticaria",
            "angioedema",
            "erythema",
            "vesiculobullous",
        ],
        "Psychiatry": [
            "depression",
            "anxiety",
            "schizophrenia",
            "bipolar",
            "mania",
            "psychosis",
            "mental illness",
            "eating disorder",
            "anorexia",
            "bulimia",
            "ocd",
            "phobia",
            "panic",
            "ptsd",
            "alcohol dependence",
            "substance abuse",
            "drug addiction",
            "suicide",
            "self harm",
            "delirium",
            "dementia psychiatry",
            "mental status",
        ],
        "Rheumatology": [
            "arthritis",
            "rheumatoid arthritis",
            "oa",
            "osteoarthritis",
            "sle",
            "lupus",
            "ankylosing spondylitis",
            "reactive arthritis",
            "psoriatic arthritis",
            "gout",
            "pseudogout",
            "scleroderma",
            "sjogren",
            "dermatomyositis",
            "polymyositis",
            "vasculitis",
        ],
        "Infectious Disease": [
            "infection",
            "fever",
            "sepsis",
            "septicemia",
            "bacteremia",
            "tetanus",
            "rabies medicine",
            "enteric fever",
            "typhoid",
            "dengue fever",
            "malaria medicine",
            "leptospirosis",
            "scrub typhus",
            "melioidosis",
            "brucellosis",
            "leprosy medicine",
            "hansen",
            "filaria",
        ],
    },
    "General Surgery": {
        "Gastrointestinal Surgery": [
            "appendicitis",
            "cholecystitis",
            "hernia surgery",
            "inguinal hernia",
            "femoral hernia",
            "umbilical hernia",
            "anal fissure",
            "hemorrhoids",
            "fistula",
            "pilonidal",
            "colorectal surgery",
            "gastric surgery",
            "bowel surgery",
            "gi surgery",
            "abdominal surgery",
            "thyroid surgery",
            "breast surgery",
            "mastectomy",
            "lump",
            "biopsy surgery",
            "pyelolithotomy",
            "nephrolithiasis surgery",
            "pyonephrosis",
            "renal calculus",
            "laparoscopic",
            "appendectomy",
            "cholecystectomy",
            "herniorrhaphy",
            "hernioplasty",
            "colostomy",
            "ileostomy",
            "gastrectomy",
            "colectomy",
            "hemicolectomy",
            "splenectomy",
            "pancreatectomy",
            " Whipple",
            "pancreaticoduodenectomy",
            "fundoplication",
            "bariatric",
            "gastric bypass",
            "barrett",
            "peptic ulcer surgery",
            "intestinal obstruction",
            "sbo",
            "aio",
        ],
        "Urology": [
            "kidney stone surgery",
            "ureteric",
            "bladder surgery",
            "prostate surgery",
            "urethral",
            "testicular surgery",
            "varicocele",
            "hydrocele",
            "circumcision",
            "epididymal",
            "urolithiasis surgery",
            "nephrectomy",
            "cystectomy",
            "turp",
            "renin",
            "uroflowmetry",
            "cystoscopy",
            "ureteroscopy",
            "pcnl",
            "eswl",
            "prostatectomy",
            "orchidectomy",
            "orchiopexy",
            "epididymectomy",
            "vasectomy",
            "meatotomy",
            "pyeloplasty",
            "kidney transplant surgery",
        ],
        "Cardiothoracic": [
            "thoracic surgery",
            "lung surgery",
            "pleural surgery",
            "mediastinal",
            "esophagus surgery",
            "cardiac surgery",
            "cabg",
            "valve surgery",
            "vvsd",
            " ASD",
            " PDA",
            "thyroidectomy",
            "parathyroidectomy",
            "pneumonectomy",
            "lobectomy",
            "wedge resection",
            "decortication",
            "thoracotomy",
            "vats",
            "pericardiocentesis",
            "median sternotomy",
            "bypass surgery",
            "valve replacement",
            "valve repair",
            "mitral",
            "aortic valve",
            "tricuspid",
            "pericardiectomy",
            "mediastinoscopy",
            "thoracoscopy",
        ],
        "Vascular": [
            "varicose vein",
            "dvt",
            "deep vein thrombosis",
            "aneurysm",
            "vascular surgery",
            "arterial disease",
            " venous disease",
            "lymphangioma",
            "lymphadenopathy surgery",
            "bypass graft",
            "endarterectomy",
            "thromboendarterectomy",
            "embolectomy",
            "amputation",
            "fistula creation",
            " av fistula",
            "dialysis access",
        ],
        "Endocrine Surgery": [
            "parathyroid surgery",
            "adrenal surgery",
            "pheochromocytoma surgery",
            "insulinoma",
            "surgical endocrinology",
            "adrenalectomy",
            "surgical management endocrine",
        ],
        "Oncology Surgery": [
            "cancer surgery",
            "tumor surgery",
            "oncologic surgery",
            "surgical oncology",
            "margins",
            "lymphadenectomy",
            "sentinel node",
            "mastectomy surgery",
            "lumpectomy",
            "wide local excision",
            "radical mastectomy",
            "modified radical",
            "hysterectomy oncology",
            " Wertheim",
            "exenteration",
            "debulking surgery",
            "hot biopsy",
            "fnac",
        ],
        "Trauma Surgery": [
            "trauma surgery",
            "polytrauma",
            "head injury surgery",
            "abdominal trauma",
            "chest trauma",
            "fracture surgery",
            "emergency surgery",
            "atv",
            "damage control",
            "resuscitative",
            "splenectomy trauma",
            "laparotomy trauma",
        ],
    },
    "Obstetrics": {
        "Pregnancy": [
            "pregnancy",
            "gestation",
            "prenatal",
            "antenatal",
            " Trimester",
            "first trimester",
            "second trimester",
            "third trimester",
            "maternal",
            "fetal",
            "胎",
            "abortion",
            "miscarriage",
            "ectopic pregnancy",
            "molar pregnancy",
            "hyperemesis gravidarum",
            "multiple pregnancy",
            "twin",
        ],
        "Labor & Delivery": [
            "labor",
            "delivery",
            "childbirth",
            "labour",
            "puerperium",
            "postpartum",
            "parturition",
            "cervix labor",
            "uterus labor",
            "augmentation",
            "oxytocin",
            "induction labor",
            "cesarean",
            "csection",
            "vaginal delivery",
            "normal delivery",
            " Assisted delivery",
            "forceps",
            "vacuum",
        ],
        "Complications": [
            "pre eclampsia",
            "eclampsia",
            "pih",
            "gestational hypertension",
            "gestational diabetes",
            "aptt",
            "abruption",
            "placenta previa",
            "uterine rupture",
            "postpartum hemorrhage",
            "pph",
            "septic abortion",
            "incomplete abortion",
            "threatened abortion",
            "habitual abortion",
            "dystocia",
            "shoulder dystocia",
            "cord prolapse",
            "fetal distress",
        ],
    },
    "Gynaecology": {
        "Menstrual": [
            "menstrual",
            "dysmenorrhea",
            "menorrhagia",
            "metrorrhagia",
            "oligomenorrhea",
            "amenorrhea",
            "polymenorrhea",
            "abnormal uterine bleeding",
            "puberty",
            "menarche",
            "menopause",
            "perimenopause",
            "perimenopausal",
            "pcos",
            "polycystic ovarian",
            "hirsutism",
        ],
        "Infertility": [
            "infertility",
            "subfertility",
            "ivf",
            "assisted reproductive",
            "art",
            "iui",
            "ovulation induction",
            "hyperstimulation",
            "icsi",
            "embryo transfer",
            "endometriosis",
            "adhesiolysis",
        ],
        "Contraception": [
            "contraception",
            "contraceptive",
            "ocp",
            "oral pill",
            "copper t",
            "iucd",
            "iud",
            "emergency contraception",
            "mtp",
            "medical termination",
            "mifepristone",
            "misoprostol",
            "sterilization",
            "tubectomy",
            "vasectomy",
        ],
        "Tumor": [
            "fibroid",
            "leiomyoma",
            "endometrial carcinoma",
            "cervical cancer",
            "ovarian tumor",
            "gynae cancer",
            "carcinoma cervix",
            "carcinoma endometrium",
            "carcinoma ovary",
            "gtd",
            "molar pregnancy gynae",
        ],
    },
    "Paediatrics": {
        "Growth & Nutrition": [
            "growth",
            "development",
            "anthropometry",
            "height weight",
            "failure to thrive",
            "faltering growth",
            "undernutrition",
            "stunting",
            "wasting",
            "nutrition paed",
            "protein energy malnutrition",
            "marasmus",
            "kwashiorkor",
            "bmi pediatric",
            "growth chart",
            "road to health",
        ],
        "Neonatology": [
            "neonate",
            "newborn",
            "preterm",
            "low birth weight",
            "lbw",
            "nbw",
            "birth asphyxia",
            "respiratory distress syndrome",
            "hyaline membrane",
            "necrotizing enterocolitis",
            "kernicterus",
            "neonatal jaundice",
            " Rh incompatibility",
            "hemolytic disease newborn",
            "neonatal sepsis",
            "birth weight",
            "prematurity",
            "apgar",
            "resuscitation newborn",
        ],
        "Pediatric Infectious": [
            "childhood infection",
            "pediatric infection",
            "septicemia child",
            "meningitis child",
            "encephalitis child",
            "diarrhea child",
            "gi infection child",
            "respiratory infection child",
            "otitis media child",
            "pneumonia child",
            "tuberculosis child",
        ],
        "Pediatric Respiratory": [
            "asthma child",
            "bronchiolitis",
            "croup",
            "epiglottitis",
            "diphtheria child",
            "whooping cough",
            "pertussis",
            "neumonia pediatric",
        ],
        "Development": [
            "developmental delay",
            "milestone",
            "cp",
            "cerebral palsy",
            "down syndrome",
            "autism",
            "asd",
            "learning disability",
            "intellectual disability",
            "developmental disorder",
            "attention deficit",
            "adhd",
        ],
    },
    "ENT": {
        "Ear": [
            "ear disease",
            "hearing loss",
            "deafness",
            "otalgia",
            "otorrhea",
            "tinnitus",
            "vertigo",
            "meniere",
            "otitis media",
            "csom",
            "aom",
            "OME",
            "cholesteatoma",
            "vestibular",
            "cochlear",
            "tympanic membrane",
            "ossicular",
            "mastoid",
            "stapedectomy",
            "audiometry",
        ],
        "Nose": [
            "nose disease",
            "epistaxis",
            "nasal",
            "sinusitis",
            "rhinitis",
            "allergic rhinitis",
            "ar",
            "deviated septum",
            "dns",
            "nasal polyp",
            "fess",
            "functional endoscopic",
            "antrostomy",
        ],
        "Throat ENT": [
            "throat",
            "tonsillitis",
            "adenoid",
            "pharyngitis",
            "laryngitis",
            "hoarseness",
            "dysphonia",
            "stridor",
            "airway obstruction",
            "foreign body throat",
            "obstructive sleep apnea",
            "osa",
            "uvulopalatopharyngoplasty",
            "tracheostomy ENT",
        ],
        "Head & Neck ENT": [
            "neck mass",
            "goiter ent",
            "thyroid ent",
            "parathyroid ent",
            "salivary gland",
            "parotid",
            "submandibular",
            " Ludwig angina",
            "cervical lymphadenopathy ent",
        ],
    },
    "Ophthalmology": {
        "Cornea & Refractive": [
            "corneal",
            "refractive error",
            "myopia",
            "hypermetropia",
            "astigmatism",
            "presbyopia",
            "keratitis",
            "corneal ulcer",
            "dry eye",
            "keratoconus",
            "lasik",
            " cataract ophthalm",
        ],
        "Glaucoma": [
            "glaucoma",
            "iop",
            "intraocular pressure",
            "tonometry",
            "open angle glaucoma",
            "angle closure glaucoma",
            "primary glaucoma",
            "secondary glaucoma",
            "neovascular glaucoma",
            " congenital glaucoma",
        ],
        "Retina": [
            "retinal",
            "retinitis",
            "retinopathy",
            "diabetic retinopathy",
            "hypertensive retinopathy",
            "retinal detachment",
            "macular",
            "macular degeneration",
            "amd",
            "cmo",
            "retinal artery",
            "retinal vein",
            "roc",
            "brvo",
            "crao",
            "crvo",
        ],
        "Lens": [
            "cataract",
            "lens",
            "aphakia",
            "pseudophakia",
            "intraocular lens",
            "iol",
            "surgical cataract",
        ],
        "Pediatric Ophthalm": [
            "squint",
            "strabismus",
            "amblyopia",
            "lazy eye",
            "childhood blindness",
            "retinopathy of prematurity",
            "rop",
            "congenital cataract",
        ],
    },
    "Radiology": {
        "X-ray": [
            "xray",
            "x ray",
            "radiograph",
            "chest x ray",
            "cxr",
            "abdominal x ray",
            "xray chest",
            "bone x ray",
            "joint x ray",
            "skull x ray",
            "kUB",
        ],
        "CT & MRI": [
            "ct scan",
            "mri",
            "computed tomography",
            "magnetic resonance",
            "ct brain",
            "ct abdomen",
            "mri brain",
            "mri spine",
            "ct pulmonary angiography",
            "ctpa",
        ],
        "Ultrasound": [
            "ultrasound",
            "usg",
            "sonography",
            " doppler",
            "color doppler",
            "obstetric ultrasound",
            "transvaginal",
            "tvS",
        ],
        "Intervention": [
            "interventional radiology",
            "angioplasty",
            "stent",
            "embolization",
            "tace",
            "radiofrequency ablation",
        ],
    },
    "Anaesthesia": {
        "General": [
            "general anesthesia",
            "gas anesthesia",
            "iv anesthesia",
            "induction",
            "maintenance anesthesia",
            "emergence",
            "monitoring anesthesia",
        ],
        "Regional": [
            "regional anesthesia",
            "spinal",
            "epidural",
            "nerve block",
            "brachial plexus block",
            " Bier block",
            "spinal anesthesia",
            "epidural anesthesia",
        ],
        "Local": [
            "local anesthetic",
            "lignocaine",
            "bupivacaine",
            "tumescent",
            "tocaine",
        ],
        "Critical Care": [
            "icu",
            "ventilator",
            "mechanical ventilation",
            "critical care",
            "sepsis icu",
            "shock icu",
            " multi organ",
            "organ failure",
            "arga",
        ],
    },
    "Orthopaedics": {
        "Fractures": [
            "fracture",
            "dislocation",
            "ligament injury",
            "bone injury",
            "closed fracture",
            "open fracture",
            "compound fracture",
            "pathological fracture",
            "stress fracture",
            "avulsion",
            "fracture healing",
            "compartment syndrome",
        ],
        "Joints": [
            "joint",
            "arthritis ortho",
            "osteoarthritis",
            "rheumatoid ortho",
            "septic arthritis",
            "gout ortho",
            "bursitis",
            "tendinitis",
            "tenosynovitis",
            " frozen shoulder",
            "adhesive capsulitis",
            "rotator cuff",
        ],
        "Spine": [
            "spine",
            "vertebral",
            "spondylosis",
            "spondylolisthesis",
            "prolapsed disc",
            "pivd",
            "herniated disc",
            "spinal cord compression",
            "spinal injury",
            "paraplegia",
            "quadriplegia",
            "tb spine",
            "pott",
        ],
        "Pediatric Ortho": [
            "cdh",
            "developmental dysplasia hip",
            "club foot",
            "talipes",
            "cerebral palsy ortho",
            "osteogenesis imperfecta",
            " Perthes disease",
            "slipped capital femoral",
            "scurvy",
            "bone dysplasia",
        ],
        "Trauma": [
            "polytrauma ortho",
            "road traffic accident",
            "rta",
            "high energy injury",
            "crush injury",
            "flail chest",
        ],
    },
}


def classify_topic(text, subject):
    text_lower = text.lower()
    subject_rules = TOPIC_RULES.get(subject, {})
    for topic, keywords in subject_rules.items():
        for kw in keywords:
            if kw.lower() in text_lower:
                return topic
    return "General"


def classify_topics(qs):
    for q in qs:
        if q.get("topic_clean", "").lower() in ["general", "unknown"]:
            q["topic_clean"] = classify_topic(
                q.get("question_text", ""), q.get("subject_clean", "")
            )
    return qs
